/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactSubmission {
  'id' : SubmissionId,
  'name' : string,
  'businessType' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export interface PartialLead {
  'id' : PartialLeadId,
  'regulatoryHurdle' : string,
  'email' : string,
  'timestamp' : bigint,
  'industry' : string,
}
export type PartialLeadId = bigint;
export type SubmissionId = bigint;
export interface WizardApplication {
  'id' : WizardApplicationId,
  'hasFein' : boolean,
  'fein' : string,
  'name' : string,
  'businessName' : string,
  'regulatoryHurdle' : string,
  'email' : string,
  'timestamp' : bigint,
  'phone' : string,
  'industry' : string,
}
export type WizardApplicationId = bigint;
export interface _SERVICE {
  'getAllPartialLeads' : ActorMethod<[], Array<PartialLead>>,
  'getAllSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getAllWizardApplications' : ActorMethod<[], Array<WizardApplication>>,
  'getTotalSubmissions' : ActorMethod<[], bigint>,
  'getTotalWizardApplications' : ActorMethod<[], bigint>,
  'savePartialLead' : ActorMethod<[string, string, string], PartialLeadId>,
  'submitContactForm' : ActorMethod<
    [string, string, string, string, string],
    SubmissionId
  >,
  'submitWizardApplication' : ActorMethod<
    [string, string, string, string, string, string, string, boolean],
    WizardApplicationId
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];