/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BlogPostId = IDL.Nat;
export const BlogPost = IDL.Record({
  'id' : BlogPostId,
  'title' : IDL.Text,
  'publishDate' : IDL.Text,
  'body' : IDL.Text,
  'published' : IDL.Bool,
  'author' : IDL.Text,
  'readTime' : IDL.Text,
  'timestamp' : IDL.Int,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const PartialLeadId = IDL.Nat;
export const PartialLead = IDL.Record({
  'id' : PartialLeadId,
  'regulatoryHurdle' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : IDL.Int,
  'industry' : IDL.Text,
});
export const PartnerLeadId = IDL.Nat;
export const PartnerLead = IDL.Record({
  'id' : PartnerLeadId,
  'contactName' : IDL.Text,
  'partnershipType' : IDL.Text,
  'description' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : IDL.Int,
  'companyName' : IDL.Text,
  'phone' : IDL.Text,
});
export const SubmissionId = IDL.Nat;
export const ContactSubmission = IDL.Record({
  'id' : SubmissionId,
  'name' : IDL.Text,
  'businessType' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});
export const WizardApplicationId = IDL.Nat;
export const WizardApplication = IDL.Record({
  'id' : WizardApplicationId,
  'hasFein' : IDL.Bool,
  'fein' : IDL.Text,
  'name' : IDL.Text,
  'businessName' : IDL.Text,
  'regulatoryHurdle' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
  'industry' : IDL.Text,
});

export const idlService = IDL.Service({
  'createBlogPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [BlogPostId],
      [],
    ),
  'deleteBlogPost' : IDL.Func([BlogPostId], [IDL.Bool], []),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllPartialLeads' : IDL.Func([], [IDL.Vec(PartialLead)], ['query']),
  'getAllPartnerLeads' : IDL.Func([], [IDL.Vec(PartnerLead)], ['query']),
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
  'getAllWizardApplications' : IDL.Func(
      [],
      [IDL.Vec(WizardApplication)],
      ['query'],
    ),
  'getBlogPost' : IDL.Func([BlogPostId], [IDL.Opt(BlogPost)], ['query']),
  'getPublishedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getTotalPartnerLeads' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalSubmissions' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalWizardApplications' : IDL.Func([], [IDL.Nat], ['query']),
  'publishBlogPost' : IDL.Func([BlogPostId], [IDL.Bool], []),
  'savePartialLead' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [PartialLeadId],
      [],
    ),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [SubmissionId],
      [],
    ),
  'submitPartnerLead' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [PartnerLeadId],
      [],
    ),
  'submitWizardApplication' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [WizardApplicationId],
      [],
    ),
  'unpublishBlogPost' : IDL.Func([BlogPostId], [IDL.Bool], []),
  'updateBlogPost' : IDL.Func(
      [
        BlogPostId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BlogPostId = IDL.Nat;
  const BlogPost = IDL.Record({
    'id' : BlogPostId,
    'title' : IDL.Text,
    'publishDate' : IDL.Text,
    'body' : IDL.Text,
    'published' : IDL.Bool,
    'author' : IDL.Text,
    'readTime' : IDL.Text,
    'timestamp' : IDL.Int,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const PartialLeadId = IDL.Nat;
  const PartialLead = IDL.Record({
    'id' : PartialLeadId,
    'regulatoryHurdle' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : IDL.Int,
    'industry' : IDL.Text,
  });
  const PartnerLeadId = IDL.Nat;
  const PartnerLead = IDL.Record({
    'id' : PartnerLeadId,
    'contactName' : IDL.Text,
    'partnershipType' : IDL.Text,
    'description' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : IDL.Int,
    'companyName' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SubmissionId = IDL.Nat;
  const ContactSubmission = IDL.Record({
    'id' : SubmissionId,
    'name' : IDL.Text,
    'businessType' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  const WizardApplicationId = IDL.Nat;
  const WizardApplication = IDL.Record({
    'id' : WizardApplicationId,
    'hasFein' : IDL.Bool,
    'fein' : IDL.Text,
    'name' : IDL.Text,
    'businessName' : IDL.Text,
    'regulatoryHurdle' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
    'industry' : IDL.Text,
  });
  
  return IDL.Service({
    'createBlogPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [BlogPostId],
        [],
      ),
    'deleteBlogPost' : IDL.Func([BlogPostId], [IDL.Bool], []),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllPartialLeads' : IDL.Func([], [IDL.Vec(PartialLead)], ['query']),
    'getAllPartnerLeads' : IDL.Func([], [IDL.Vec(PartnerLead)], ['query']),
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
    'getAllWizardApplications' : IDL.Func(
        [],
        [IDL.Vec(WizardApplication)],
        ['query'],
      ),
    'getBlogPost' : IDL.Func([BlogPostId], [IDL.Opt(BlogPost)], ['query']),
    'getPublishedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getTotalPartnerLeads' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalSubmissions' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalWizardApplications' : IDL.Func([], [IDL.Nat], ['query']),
    'publishBlogPost' : IDL.Func([BlogPostId], [IDL.Bool], []),
    'savePartialLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [PartialLeadId],
        [],
      ),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [SubmissionId],
        [],
      ),
    'submitPartnerLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [PartnerLeadId],
        [],
      ),
    'submitWizardApplication' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [WizardApplicationId],
        [],
      ),
    'unpublishBlogPost' : IDL.Func([BlogPostId], [IDL.Bool], []),
    'updateBlogPost' : IDL.Func(
        [
          BlogPostId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };