/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type SubmissionId = bigint;
export interface BlogPost {
    id: BlogPostId;
    title: string;
    publishDate: string;
    body: string;
    published: boolean;
    author: string;
    readTime: string;
    timestamp: bigint;
    excerpt: string;
    category: string;
}
export type WizardApplicationId = bigint;
export interface PartnerLead {
    id: PartnerLeadId;
    contactName: string;
    partnershipType: string;
    description: string;
    email: string;
    timestamp: bigint;
    companyName: string;
    phone: string;
}
export interface ContactSubmission {
    id: SubmissionId;
    name: string;
    businessType: string;
    email: string;
    message: string;
    timestamp: bigint;
    phone: string;
}
export type BlogPostId = bigint;
export type PartialLeadId = bigint;
export interface WizardApplication {
    id: WizardApplicationId;
    hasFein: boolean;
    fein: string;
    name: string;
    businessName: string;
    regulatoryHurdle: string;
    email: string;
    timestamp: bigint;
    phone: string;
    industry: string;
}
export interface PartialLead {
    id: PartialLeadId;
    regulatoryHurdle: string;
    email: string;
    timestamp: bigint;
    industry: string;
}
export type PartnerLeadId = bigint;
export interface backendInterface {
    createBlogPost(title: string, category: string, excerpt: string, body: string, author: string, readTime: string, publishDate: string): Promise<BlogPostId>;
    deleteBlogPost(id: BlogPostId): Promise<boolean>;
    getAllBlogPosts(): Promise<Array<BlogPost>>;
    getAllPartialLeads(): Promise<Array<PartialLead>>;
    getAllPartnerLeads(): Promise<Array<PartnerLead>>;
    getAllSubmissions(): Promise<Array<ContactSubmission>>;
    getAllWizardApplications(): Promise<Array<WizardApplication>>;
    getBlogPost(id: BlogPostId): Promise<BlogPost | null>;
    getPublishedBlogPosts(): Promise<Array<BlogPost>>;
    getTotalPartnerLeads(): Promise<bigint>;
    getTotalSubmissions(): Promise<bigint>;
    getTotalWizardApplications(): Promise<bigint>;
    publishBlogPost(id: BlogPostId): Promise<boolean>;
    savePartialLead(email: string, industry: string, regulatoryHurdle: string): Promise<PartialLeadId>;
    submitContactForm(name: string, email: string, phone: string, businessType: string, message: string): Promise<SubmissionId>;
    submitPartnerLead(companyName: string, contactName: string, email: string, phone: string, partnershipType: string, description: string): Promise<PartnerLeadId>;
    submitWizardApplication(industry: string, regulatoryHurdle: string, name: string, email: string, phone: string, businessName: string, fein: string, hasFein: boolean): Promise<WizardApplicationId>;
    unpublishBlogPost(id: BlogPostId): Promise<boolean>;
    updateBlogPost(id: BlogPostId, title: string, category: string, excerpt: string, body: string, author: string, readTime: string, publishDate: string): Promise<boolean>;
}
import type { BlogPost as _BlogPost } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createBlogPost(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string): Promise<BlogPostId> {
        if (this.processError) {
            try {
                const result = await this.actor.createBlogPost(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBlogPost(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async deleteBlogPost(arg0: BlogPostId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBlogPost(arg0);
            return result;
        }
    }
    async getAllBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBlogPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBlogPosts();
            return result;
        }
    }
    async getAllPartialLeads(): Promise<Array<PartialLead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPartialLeads();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPartialLeads();
            return result;
        }
    }
    async getAllPartnerLeads(): Promise<Array<PartnerLead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPartnerLeads();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPartnerLeads();
            return result;
        }
    }
    async getAllSubmissions(): Promise<Array<ContactSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubmissions();
            return result;
        }
    }
    async getAllWizardApplications(): Promise<Array<WizardApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWizardApplications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWizardApplications();
            return result;
        }
    }
    async getBlogPost(arg0: BlogPostId): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPost(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPost(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublishedBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedBlogPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedBlogPosts();
            return result;
        }
    }
    async getTotalPartnerLeads(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalPartnerLeads();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalPartnerLeads();
            return result;
        }
    }
    async getTotalSubmissions(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalSubmissions();
            return result;
        }
    }
    async getTotalWizardApplications(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalWizardApplications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalWizardApplications();
            return result;
        }
    }
    async publishBlogPost(arg0: BlogPostId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.publishBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishBlogPost(arg0);
            return result;
        }
    }
    async savePartialLead(arg0: string, arg1: string, arg2: string): Promise<PartialLeadId> {
        if (this.processError) {
            try {
                const result = await this.actor.savePartialLead(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePartialLead(arg0, arg1, arg2);
            return result;
        }
    }
    async submitContactForm(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<SubmissionId> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async submitPartnerLead(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<PartnerLeadId> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPartnerLead(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPartnerLead(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async submitWizardApplication(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: boolean): Promise<WizardApplicationId> {
        if (this.processError) {
            try {
                const result = await this.actor.submitWizardApplication(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitWizardApplication(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async unpublishBlogPost(arg0: BlogPostId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.unpublishBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unpublishBlogPost(arg0);
            return result;
        }
    }
    async updateBlogPost(arg0: BlogPostId, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBlogPost(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBlogPost(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BlogPost]): BlogPost | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
